---
title: "Analysis of Units (An-Us)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{anus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(ricu)
library(ggplot2)
take_quants <- function(x, probs) {
  qq <- quantile(x, probs = probs)
  return(x[x >= qq[1] & x <= qq[2]])
}
```

## Analysis of Units

We demonstrate how to verify whether the units across different datasets match. For example, we take 5 different items:

```{r concept-range}
data_src <- c("mimic_demo", "eicu_demo")
concept_range <- c("mean_bp", "lactate" , "creatinine", "bilirubin_total", "platelet_count")
```

We plot the density of the features and report their median values:

```{r anus, echo=FALSE, fig.width=6, message=FALSE}
dict <- get_config("concept-dict")

for (conc in concept_range) {
  med <- rep(NA, 2)
  df <- NULL
  for(src in 1:2) {
    
    if(is.null(dict[[conc]][["sources"]][[data_src[src]]])) next
    
    tbl <- load_dictionary(source = data_src[src], concepts = conc, id_type = "icustay")
    
    x <- tbl[, get(conc)]
    med[src] <- median(x, na.rm = TRUE)
    
    x <- take_quants(x, c(0.05, 0.95))
    
    if(is.null(x)) next
    if(length(x) == 0) next
    df <- rbind(
      df,
      data.frame(
        value = x,
        source = data_src[src]
      )
    )
  }
  vals <- paste0(round(med, 2), collapse = ", ")
  vals <- paste0("(", vals, ")")
  tit <- paste0(conc, ": median values ", vals)
  p <- ggplot(df, aes(x = value, fill = source)) +
  geom_density(alpha=0.5) + xlab(conc) + theme_minimal(15) + ggtitle(tit)
  print(p)
  #if(min(med, na.rm = T)/max(med, na.rm = T) < 0.9) print(p)
}
```

