name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pre-commit-checks:
    name: "Linux - pre-commit checks"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_USE_MICROMAMBA: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.5.2
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@d05808540d968a55ca33c798e0661fb98f533c73
        with:
          micromamba-version: 1.5.10-0
      - name: Add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0